title: Oscar Johnson
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Game developer
  <br><br>
  Young and aspiring student with a passion for video games, currently studying Games Technology(Bsc) at The university of the west of England (UWE) with a background in Computer Science, Physics and Information Technology. I've always had a passion for computers, video games and programing. For as long as I can remember it has been my dream to work a key role in a development team for a major studio.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
