title: Oscar Johnson
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Game developer
  <br><br>
  I am a young and aspiring graduate (First class, BSc) with a passion for video games!
  Feel free to browse my projects or get in touch via the links below.
  <a href="https://www.JohnnersUK.github.io/pdf/OscarJohnson.pdf">Here's a copy of my CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/oscar-johnson-uk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
